# Generated by Django 3.0.8 on 2020-12-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='camera',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtuber',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
