# Generated by Django 3.0.8 on 2020-12-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20201228_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera',
            field=models.CharField(choices=[('canon', 'canon'), ('fuji', 'fuji'), ('nikon', 'nikon'), ('sony', 'sony')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('education', 'education'), ('comedy', 'comedy'), ('gaming', 'gaming'), ('cooking', 'cooking')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255, null=True),
        ),
    ]
