# Generated by Django 3.0.8 on 2020-12-28 17:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20201228_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='decription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
